#!/usr/bin/with-contenv sh

#font for agnoster
yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
sed -i 's/plugins=(git)/plugins=(git vagrant zsh-autosuggestions zsh-syntax-highlighting)/g' $HOME/.zshrc

#aapanel
# apt-get install selinux-basics selinux-policy-default auditd
# wget -O install.sh http://www.aapanel.com/script/install-ubuntu_6.0_en.sh && bash install.sh